apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue{{ .Values.deployment.name }}
spec:
  selector:
    matchLabels:
      app: queue{{ .Values.deployment.name }}
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: queue{{ .Values.deployment.name }}
    spec:
      containers:
      - name: queue{{ .Values.deployment.name }}
        image: richardchesterwood/k8s-fleetman-queue:release2{{ .Values.image.repository }}:{{ .Values.image.tag }}
