apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-svc
spec:
  selector:
    app: {{ .Values.deployment.name }}

  ports:
    - name: {{ .Values.service.ports.name }}
      port: {{ .Values.service.ports.port }}
      nodePort: {{ .Values.service.ports.nodePort }}

    - name: {{ .Values.service.ports.name }}
      port: {{ .Values.service.ports.port }}
    
  type: {{ .Values.service.type }}
