apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-svc
spec:
  selector:
    app: {{ .Values.deployment.name }}

  ports:
    - name: {{ .Values.service.ports[0].name }}
      port: {{ .Values.service.ports[0].port }}
      nodePort: {{ .Values.service.ports[0].nodePort }}

    - name: {{ .Values.service.ports[1].name }}
      port: {{ .Values.service.ports[1].port }}
    
  type: {{ .Values.service.type }}
