apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue{{ .Values.deployment.name }}-svc

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: queue{{ .Values.deployment.name }}

  ports:
    - name: http
      port: 8161
      nodePort: 30010

    - name: endpoint
      port: 61616
