apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue{{ .Values.deployment.name }}-svc

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: queue{{ .Values.deployment.name }}

  ports:
    - name: http{{ .Values.service.ports[0].name }}
      port: 8161{{ .Values.service.ports[0].port }}
      nodePort: 30010{{ .Values.service.ports[0].nodePort }}

    - name: endpoint{{ .Values.service.ports[1].name }}
      port: 61616{{ .Values.service.ports[1].port }}
  
